package com.trainflow.document;

import com.trainflow.shared.error.ApiError;
import com.trainflow.trainingcase.*;
import java.io.IOException;
import java.nio.file.Path;
import java.time.Instant;
import java.util.*;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class DocumentService {
 private static final Map<DocumentType,String> NAMES=Map.of(DocumentType.PROGRAM,"Programme PDF",DocumentType.QUOTE,"Devis",DocumentType.AGREEMENT,"Convention",DocumentType.ATTENDANCE_SHEET,"Feuille de présence",DocumentType.CERTIFICATE,"Attestation");
 private static final Map<DocumentType,String> PREFIXES=Map.of(DocumentType.PROGRAM,"programme",DocumentType.QUOTE,"devis",DocumentType.AGREEMENT,"convention",DocumentType.ATTENDANCE_SHEET,"feuille_presence",DocumentType.CERTIFICATE,"attestation");
 private final TrainingDocumentRepository documents; private final TrainingCaseRepository cases; private final DocumentStorage storage; private final PdfRenderer renderer;
 public DocumentService(TrainingDocumentRepository documents,TrainingCaseRepository cases,DocumentStorage storage,PdfRenderer renderer){this.documents=documents;this.cases=cases;this.storage=storage;this.renderer=renderer;}
 @Transactional(readOnly=true) public List<DocumentResponse> list(UUID caseId){requireCase(caseId);return documents.findByTrainingCaseIdOrderByDocumentType(caseId).stream().map(DocumentResponse::from).toList();}
 @Transactional public List<DocumentResponse> initialize(UUID caseId){var c=locked(caseId);requireDocumentStage(c);for(var type:DocumentType.values())if(documents.findByTrainingCaseIdAndDocumentType(caseId,type).isEmpty())documents.save(new TrainingDocument(caseId,type,NAMES.get(type)));if(c.getStatus()==TrainingCaseStatus.TARIFICATION_VALIDEE)c.setStatus(TrainingCaseStatus.DOCUMENTS_A_GENERER);return documents.findByTrainingCaseIdOrderByDocumentType(caseId).stream().map(DocumentResponse::from).toList();}
 @Transactional public DocumentResponse generate(UUID caseId,DocumentType type){var c=locked(caseId);if(c.getStatus()==TrainingCaseStatus.TARIFICATION_VALIDEE)initialize(caseId);requireDocumentStage(c);var d=documents.findByTrainingCaseIdAndDocumentType(caseId,type).orElseThrow(()->new ApiError(HttpStatus.NOT_FOUND,"TRAINING_DOCUMENT_NOT_FOUND","Le document est introuvable."));String old=d.getRelativePath();try{var snapshot=new LinkedHashMap<String,Object>();snapshot.put("reference",c.getReference());snapshot.put("theme",c.getTheme());snapshot.put("document_type",type.name());byte[] bytes=renderer.render(type,snapshot);var stored=storage.store(caseId,type,bytes);d.setStatus(DocumentStatus.GENERATED);d.setInternalFilename(stored.filename());d.setOriginalFilename(PREFIXES.get(type)+"_"+c.getReference()+".pdf");d.setRelativePath(stored.relativePath());d.setMimeType("application/pdf");d.setFileSize(stored.size());d.setSha256(stored.sha256());d.setSnapshotData(snapshot);d.setGenerationError(null);d.setGeneratedAt(Instant.now());documents.save(d);if(old!=null&&!old.equals(stored.relativePath()))storage.delete(old);refresh(c);return DocumentResponse.from(d);}catch(Exception error){d.setStatus(DocumentStatus.FAILED);d.setGenerationError("La génération du PDF a échoué.");documents.save(d);throw new ApiError(HttpStatus.INTERNAL_SERVER_ERROR,"DOCUMENT_GENERATION_FAILED","La génération du PDF a échoué.");}}
 @Transactional public GenerateAllResponse generateAll(UUID caseId){if(documents.findByTrainingCaseIdOrderByDocumentType(caseId).isEmpty())initialize(caseId);var results=new ArrayList<GenerateAllResponse.Result>();for(var type:DocumentType.values()){try{var response=generate(caseId,type);results.add(new GenerateAllResponse.Result(type,true,response,null));}catch(ApiError error){var current=documents.findByTrainingCaseIdAndDocumentType(caseId,type).map(DocumentResponse::from).orElse(null);results.add(new GenerateAllResponse.Result(type,false,current,error.getMessage()));}}return new GenerateAllResponse(results,results.stream().allMatch(GenerateAllResponse.Result::success));}
 @Transactional(readOnly=true) public Download download(UUID caseId,DocumentType type){requireCase(caseId);var d=documents.findByTrainingCaseIdAndDocumentType(caseId,type).filter(x->x.getStatus()==DocumentStatus.GENERATED&&x.getRelativePath()!=null).orElseThrow(()->new ApiError(HttpStatus.NOT_FOUND,"TRAINING_DOCUMENT_FILE_NOT_FOUND","Le PDF est indisponible."));Path path;try{path=storage.resolve(d.getRelativePath());}catch(IllegalArgumentException e){throw new ApiError(HttpStatus.NOT_FOUND,"TRAINING_DOCUMENT_FILE_NOT_FOUND","Le PDF est indisponible.");}if(!path.toFile().isFile())throw new ApiError(HttpStatus.NOT_FOUND,"TRAINING_DOCUMENT_FILE_NOT_FOUND","Le PDF est indisponible.");return new Download(path,d.getOriginalFilename()==null?"document.pdf":d.getOriginalFilename());}
 private void refresh(TrainingCase c){var all=documents.findByTrainingCaseIdOrderByDocumentType(c.getId());if(all.size()==DocumentType.values().length&&all.stream().allMatch(d->d.getStatus()==DocumentStatus.GENERATED&&d.getRelativePath()!=null))c.setStatus(TrainingCaseStatus.DOCUMENTS_GENERES);}
 private TrainingCase requireCase(UUID id){return cases.detailed(id).orElseThrow(()->new ApiError(HttpStatus.NOT_FOUND,"TRAINING_CASE_NOT_FOUND","Le dossier est introuvable."));} private TrainingCase locked(UUID id){return cases.locked(id).orElseThrow(()->new ApiError(HttpStatus.NOT_FOUND,"TRAINING_CASE_NOT_FOUND","Le dossier est introuvable."));}
 private void requireDocumentStage(TrainingCase c){if(!Set.of(TrainingCaseStatus.TARIFICATION_VALIDEE,TrainingCaseStatus.DOCUMENTS_A_GENERER,TrainingCaseStatus.DOCUMENTS_GENERES).contains(c.getStatus()))throw new ApiError(HttpStatus.CONFLICT,"INVALID_TRAINING_CASE_STATUS","Le statut du dossier ne permet pas cette action.");}
 public record Download(Path path,String filename){}
}
