package com.trainflow.program;
import com.trainflow.shared.error.ApiError; import com.trainflow.trainingcase.*; import com.trainflow.trainingneed.*; import java.math.*; import java.time.Instant; import java.util.*; import org.springframework.http.HttpStatus; import org.springframework.security.core.context.SecurityContextHolder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class ProgramService {
 private final TrainingProgramRepository programs;private final TrainingProgramDayRepository days;private final TrainingProgramItemRepository items;private final TrainingCaseRepository cases;private final TrainingNeedRepository needs;private final ActivityRepository activities;private final ProgramGenerationGateway generator;
 public ProgramService(TrainingProgramRepository p,TrainingProgramDayRepository d,TrainingProgramItemRepository i,TrainingCaseRepository c,TrainingNeedRepository n,ActivityRepository a,ProgramGenerationGateway g){programs=p;days=d;items=i;cases=c;needs=n;activities=a;generator=g;}
 @Transactional(readOnly=true) public ProgramResponse get(UUID caseId){caseEntity(caseId);return response(program(caseId));}
 @Transactional public ProgramResponse create(UUID caseId,ProgramRequest r){TrainingCase c=mutableCase(caseId);creationAllowed(c);if(programs.findByTrainingCaseId(caseId).isPresent())throw conflict("TRAINING_PROGRAM_ALREADY_EXISTS","Un programme existe déjà pour ce dossier.");TrainingProgram p=new TrainingProgram(caseId,value(r.title(),c.getTheme()));p.setGeneralObjectives(clean(r.generalObjectives()));p.setPrerequisites(clean(r.prerequisites()));p.setEvaluationMethod(clean(r.evaluationMethod()));programs.saveAndFlush(p);c.setStatus(TrainingCaseStatus.PROGRAMME_EN_PREPARATION);log(c,p,"TrainingProgramCreated",Map.of());return response(p);}
 @Transactional public ProgramResponse update(UUID caseId,ProgramRequest r){var cp=editable(caseId);TrainingProgram p=cp.p;if(r.title()!=null)p.setTitle(required(r.title()));if(r.generalObjectives()!=null)p.setGeneralObjectives(clean(r.generalObjectives()));if(r.prerequisites()!=null)p.setPrerequisites(clean(r.prerequisites()));if(r.evaluationMethod()!=null)p.setEvaluationMethod(clean(r.evaluationMethod()));log(cp.c,p,"TrainingProgramUpdated",Map.of());return response(p);}
 @Transactional public ProgramResponse addDay(UUID caseId,DayRequest r){var cp=editable(caseId);int pos=cp.p.getDays().size()+1;TrainingProgramDay d=new TrainingProgramDay(cp.p,value(r.title(),"Journée "+pos),pos);cp.p.getDays().add(d);days.save(d);log(cp.c,cp.p,"TrainingProgramDayAdded",Map.of("position",pos));return response(cp.p);}
 @Transactional public ProgramResponse updateDay(UUID caseId,UUID dayId,DayRequest r){var cp=editable(caseId);TrainingProgramDay d=day(cp.p,dayId);d.setTitle(required(r.title()));return response(cp.p);}
 @Transactional public ProgramResponse removeDay(UUID caseId,UUID dayId){var cp=editable(caseId);TrainingProgramDay d=day(cp.p,dayId);cp.p.getDays().remove(d);days.delete(d);normalizeDays(cp.p);return response(cp.p);}
 @Transactional public ProgramResponse moveDay(UUID caseId,UUID dayId,int delta){var cp=editable(caseId);List<TrainingProgramDay> sorted=cp.p.getDays().stream().sorted(Comparator.comparingInt(TrainingProgramDay::getPosition)).toList();int index=indexDay(sorted,dayId),target=index+delta;if(target<0||target>=sorted.size())return response(cp.p);TrainingProgramDay a=sorted.get(index),b=sorted.get(target);int pos=a.getPosition();a.setPosition(99999);days.flush();b.setPosition(pos);days.flush();a.setPosition(target+1);return response(cp.p);}
 @Transactional public ProgramResponse addItem(UUID caseId,UUID dayId,ItemRequest r){var cp=editable(caseId);TrainingProgramDay d=day(cp.p,dayId);validateParent(d,r.itemType(),r.parentId());int pos=(int)d.getItems().stream().filter(i->Objects.equals(i.getParentId(),r.parentId())).count()+1;TrainingProgramItem item=new TrainingProgramItem(d,r.itemType(),r.parentId(),required(r.title()),pos);item.setContent(clean(r.content()));item.setTheoryMinutes(r.theoryMinutes());item.setPracticeMinutes(r.practiceMinutes());if(r.methods()!=null)item.getMethods().addAll(r.methods());d.getItems().add(item);items.save(item);return response(cp.p);}
 @Transactional public ProgramResponse updateItem(UUID caseId,UUID itemId,ItemPatchRequest r){var cp=editable(caseId);TrainingProgramItem item=item(cp.p,itemId);boolean hasChildren=item.getDay().getItems().stream().anyMatch(x->item.getId().equals(x.getParentId()));int theory=r.theoryMinutes()==null?item.getTheoryMinutes():r.theoryMinutes(),practice=r.practiceMinutes()==null?item.getPracticeMinutes():r.practiceMinutes();if(hasChildren&&(theory>0||practice>0))throw bad("MODULE_WITH_CHILDREN_HAS_DIRECT_DURATION","Un module contenant des sous-modules ne peut pas porter de durée directe.");if(r.title()!=null)item.setTitle(required(r.title()));if(r.content()!=null)item.setContent(clean(r.content()));item.setTheoryMinutes(theory);item.setPracticeMinutes(practice);if(r.methods()!=null){item.getMethods().clear();item.getMethods().addAll(r.methods());}return response(cp.p);}
 @Transactional public ProgramResponse removeItem(UUID caseId,UUID itemId){var cp=editable(caseId);TrainingProgramItem item=item(cp.p,itemId);TrainingProgramDay d=item.getDay();UUID parent=item.getParentId();d.getItems().removeIf(x->x.getId().equals(itemId)||itemId.equals(x.getParentId()));items.delete(item);normalizeItems(d,parent);return response(cp.p);}
 @Transactional public ProgramResponse moveItem(UUID caseId,UUID itemId,int delta){var cp=editable(caseId);TrainingProgramItem item=item(cp.p,itemId);List<TrainingProgramItem>s=item.getDay().getItems().stream().filter(x->Objects.equals(x.getParentId(),item.getParentId())).sorted(Comparator.comparingInt(TrainingProgramItem::getPosition)).toList();int idx=s.indexOf(item),target=idx+delta;if(target<0||target>=s.size())return response(cp.p);TrainingProgramItem b=s.get(target);int pos=item.getPosition();item.setPosition(99999);items.flush();b.setPosition(pos);items.flush();item.setPosition(target+1);return response(cp.p);}
 @Transactional public ProgramResponse submit(UUID caseId){var cp=editable(caseId);validateComplete(cp.p);validateDuration(cp.p,caseId);cp.p.setSubmitted(true);cp.p.setSubmittedAt(Instant.now());cp.p.setReturnReason(null);cp.c.setStatus(TrainingCaseStatus.PROGRAMME_A_VALIDER);return response(cp.p);}
 @Transactional public ProgramResponse returnProgram(UUID caseId,String reason){TrainingCase c=mutableCase(caseId);TrainingProgram p=locked(caseId);if(c.getStatus()!=TrainingCaseStatus.PROGRAMME_A_VALIDER||p.isValidated())throw conflict("INVALID_TRAINING_CASE_STATUS","Le programme n’est pas en attente de validation.");p.setSubmitted(false);p.setSubmittedAt(null);p.setReturnedAt(Instant.now());p.setReturnReason(required(reason));c.setStatus(TrainingCaseStatus.PROGRAMME_EN_PREPARATION);return response(p);}
 @Transactional public ProgramResponse validate(UUID caseId){TrainingCase c=mutableCase(caseId);TrainingProgram p=locked(caseId);if(p.isValidated())throw conflict("TRAINING_PROGRAM_ALREADY_VALIDATED","Le programme est déjà validé.");if(c.getStatus()!=TrainingCaseStatus.PROGRAMME_A_VALIDER||!p.isSubmitted())throw conflict("INVALID_TRAINING_CASE_STATUS","Le programme n’est pas en attente de validation.");validateComplete(p);validateDuration(p,caseId);p.setValidated(true);p.setValidatedAt(Instant.now());c.setStatus(TrainingCaseStatus.PROGRAMME_VALIDE);return response(p);}
 public ProgramResponse generate(UUID caseId){return generator.generate(caseId);}
 private void creationAllowed(TrainingCase c){if(!Set.of(TrainingCaseStatus.BESOIN_COMPLETE,TrainingCaseStatus.PROGRAMME_EN_PREPARATION).contains(c.getStatus()))throw conflict("INVALID_TRAINING_CASE_STATUS","Le besoin doit être complété avant de créer le programme.");if(c.getTrainer()==null)throw conflict("TRAINER_REQUIRED","Un formateur doit être affecté.");TrainingNeed n=needs.findByTrainingCaseId(c.getId()).orElseThrow(()->new ApiError(HttpStatus.NOT_FOUND,"TRAINING_NEED_NOT_FOUND","Le besoin client est introuvable."));if(!n.isValidated())throw conflict("TRAINING_NEED_NOT_VALIDATED","Le besoin client doit être validé.");}
 private void validateComplete(TrainingProgram p){if(p.getDays().isEmpty()||p.getDays().stream().anyMatch(d->d.getItems().isEmpty()))throw bad("TRAINING_PROGRAM_INCOMPLETE","Le programme doit contenir des journées et des modules.");}
 private void validateDuration(TrainingProgram p,UUID caseId){int expected=expected(caseId),actual=totals(p)[2];if(expected!=actual)throw new ApiError(HttpStatus.BAD_REQUEST,"PROGRAM_DURATION_MISMATCH","La durée du programme ne correspond pas au besoin validé.",Map.of("expected_minutes",expected,"actual_minutes",actual));}
 private Pair editable(UUID id){TrainingCase c=mutableCase(id);TrainingProgram p=locked(id);if(c.getStatus()!=TrainingCaseStatus.PROGRAMME_EN_PREPARATION||p.isSubmitted()||p.isValidated())throw conflict("TRAINING_PROGRAM_NOT_EDITABLE","Le programme n’est pas modifiable dans son état actuel.");return new Pair(c,p);}private TrainingProgram locked(UUID id){return programs.locked(id).orElseThrow(()->new ApiError(HttpStatus.NOT_FOUND,"TRAINING_PROGRAM_NOT_FOUND","Le programme est introuvable."));}private TrainingProgram program(UUID id){return programs.findByTrainingCaseId(id).orElseThrow(()->new ApiError(HttpStatus.NOT_FOUND,"TRAINING_PROGRAM_NOT_FOUND","Le programme est introuvable."));}
 private TrainingCase mutableCase(UUID id){TrainingCase c=cases.locked(id).orElseThrow(()->new ApiError(HttpStatus.NOT_FOUND,"TRAINING_CASE_NOT_FOUND","Le dossier est introuvable."));if(c.isArchived()||c.getStatus()==TrainingCaseStatus.ANNULE)throw conflict("TRAINING_CASE_NOT_EDITABLE","Le dossier ne peut plus être modifié.");return c;}private TrainingCase caseEntity(UUID id){return cases.detailed(id).orElseThrow(()->new ApiError(HttpStatus.NOT_FOUND,"TRAINING_CASE_NOT_FOUND","Le dossier est introuvable."));}
 private TrainingProgramDay day(TrainingProgram p,UUID id){return p.getDays().stream().filter(d->d.getId().equals(id)).findFirst().orElseThrow(()->new ApiError(HttpStatus.NOT_FOUND,"TRAINING_PROGRAM_DAY_NOT_FOUND","La journée est introuvable."));}private TrainingProgramItem item(TrainingProgram p,UUID id){return p.getDays().stream().flatMap(d->d.getItems().stream()).filter(i->i.getId().equals(id)).findFirst().orElseThrow(()->new ApiError(HttpStatus.NOT_FOUND,"TRAINING_PROGRAM_ITEM_NOT_FOUND","Le module est introuvable."));}private void validateParent(TrainingProgramDay d,ProgramItemType type,UUID parent){if((type==ProgramItemType.MODULE&&parent!=null)||(type==ProgramItemType.SUBMODULE&&parent==null))throw bad("INVALID_PROGRAM_ITEM_PARENT","La hiérarchie du module est invalide.");if(parent!=null&&d.getItems().stream().noneMatch(i->i.getId().equals(parent)&&i.getItemType()==ProgramItemType.MODULE))throw bad("INVALID_PROGRAM_ITEM_PARENT","Le module parent est invalide.");}
 private void normalizeDays(TrainingProgram p){List<TrainingProgramDay>s=p.getDays().stream().sorted(Comparator.comparingInt(TrainingProgramDay::getPosition)).toList();for(int i=0;i<s.size();i++)s.get(i).setPosition(i+1);}private void normalizeItems(TrainingProgramDay d,UUID parent){List<TrainingProgramItem>s=d.getItems().stream().filter(i->Objects.equals(i.getParentId(),parent)).sorted(Comparator.comparingInt(TrainingProgramItem::getPosition)).toList();for(int i=0;i<s.size();i++)s.get(i).setPosition(i+1);}private int indexDay(List<TrainingProgramDay>d,UUID id){for(int i=0;i<d.size();i++)if(d.get(i).getId().equals(id))return i;throw new ApiError(HttpStatus.NOT_FOUND,"TRAINING_PROGRAM_DAY_NOT_FOUND","La journée est introuvable.");}
 private ProgramResponse response(TrainingProgram p){int expected=expected(p.getTrainingCaseId());List<ProgramResponse.Day>dr=p.getDays().stream().sorted(Comparator.comparingInt(TrainingProgramDay::getPosition)).map(this::dayResponse).toList();int[]t=totals(p);return new ProgramResponse(p.getId(),p.getTrainingCaseId(),p.getTitle(),p.getGeneralObjectives(),p.getPrerequisites(),p.getEvaluationMethod(),p.isSubmitted(),p.getSubmittedAt(),p.isValidated(),p.getValidatedAt(),p.getReturnedAt(),p.getReturnReason(),p.getCreatedAt(),p.getUpdatedAt(),expected,t[0],t[1],t[2],dr,null,false);}private ProgramResponse.Day dayResponse(TrainingProgramDay d){List<ProgramResponse.Item>roots=d.getItems().stream().filter(i->i.getParentId()==null).sorted(Comparator.comparingInt(TrainingProgramItem::getPosition)).map(i->itemResponse(i,d.getItems())).toList();int th=roots.stream().mapToInt(ProgramResponse.Item::theoryTotalMinutes).sum(),pr=roots.stream().mapToInt(ProgramResponse.Item::practiceTotalMinutes).sum();return new ProgramResponse.Day(d.getId(),d.getTitle(),d.getPosition(),th,pr,th+pr,roots);}private ProgramResponse.Item itemResponse(TrainingProgramItem i,List<TrainingProgramItem>all){List<ProgramResponse.Item>children=all.stream().filter(x->i.getId().equals(x.getParentId())).sorted(Comparator.comparingInt(TrainingProgramItem::getPosition)).map(x->itemResponse(x,all)).toList();int th=children.isEmpty()?i.getTheoryMinutes():children.stream().mapToInt(ProgramResponse.Item::theoryTotalMinutes).sum(),pr=children.isEmpty()?i.getPracticeMinutes():children.stream().mapToInt(ProgramResponse.Item::practiceTotalMinutes).sum();return new ProgramResponse.Item(i.getId(),i.getItemType(),i.getParentId(),i.getTitle(),i.getContent(),i.getTheoryMinutes(),i.getPracticeMinutes(),th,pr,th+pr,i.getPosition(),new ArrayList<>(i.getMethods()),children);}private int[] totals(TrainingProgram p){int th=0,pr=0;for(TrainingProgramDay d:p.getDays()){ProgramResponse.Day x=dayResponse(d);th+=x.theoryTotalMinutes();pr+=x.practiceTotalMinutes();}return new int[]{th,pr,th+pr};}private int expected(UUID id){TrainingNeed n=needs.findByTrainingCaseId(id).orElseThrow(()->new ApiError(HttpStatus.NOT_FOUND,"TRAINING_NEED_NOT_FOUND","Le besoin client est introuvable."));return n.getDurationHours()==null?0:n.getDurationHours().multiply(BigDecimal.valueOf(60)).setScale(0,RoundingMode.HALF_UP).intValue();}
 private void log(TrainingCase c,TrainingProgram p,String action,Map<String,Object>d){activities.save(new ActivityLog(admin(),c.getId(),action,"training_program",p.getId(),d));}private UUID admin(){return UUID.fromString(SecurityContextHolder.getContext().getAuthentication().getName());}private String clean(String s){return s==null||s.trim().isEmpty()?null:s.trim();}private String required(String s){String v=clean(s);if(v==null)throw bad("VALIDATION_ERROR","La valeur est obligatoire.");return v;}private String value(String a,String b){String v=clean(a);return v==null?b:v;}private ApiError conflict(String c,String m){return new ApiError(HttpStatus.CONFLICT,c,m);}private ApiError bad(String c,String m){return new ApiError(HttpStatus.BAD_REQUEST,c,m);}private record Pair(TrainingCase c,TrainingProgram p){}
}
