package com.trainflow.trainer;
import com.trainflow.shared.error.ApiError; import java.io.*; import java.nio.file.*; import java.security.*; import java.util.*; import java.util.zip.*; import org.springframework.beans.factory.annotation.Value; import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import org.springframework.web.multipart.MultipartFile;
@Service
public class CvStorageService {
 private final Path root; private final long maxBytes;
 public CvStorageService(@Value("${trainflow.storage.cv-directory}") String dir,@Value("${trainflow.storage.max-cv-file-size-mb}") long max){root=Path.of(dir).toAbsolutePath().normalize();maxBytes=max*1024*1024;try{Files.createDirectories(root);}catch(IOException e){throw new IllegalStateException(e);}}
 public StoredCv store(MultipartFile file){String name=Optional.ofNullable(file.getOriginalFilename()).orElse(""); if(name.isBlank()||name.contains("/")||name.contains("\\")||name.contains(".."))throw error("INVALID_CV_FILENAME","Le nom du fichier est invalide."); String lower=name.toLowerCase(Locale.ROOT); String mime=file.getContentType(); if(!(lower.endsWith(".pdf")&&"application/pdf".equals(mime))&&!(lower.endsWith(".docx")&&"application/vnd.openxmlformats-officedocument.wordprocessingml.document".equals(mime)))throw error("FILE_INVALID","Le CV doit être un PDF ou DOCX valide.");
  try{byte[] bytes=file.getBytes();if(bytes.length==0)throw error("FILE_INVALID","Le fichier CV est vide.");if(bytes.length>maxBytes)throw new ApiError(HttpStatus.PAYLOAD_TOO_LARGE,"FILE_TOO_LARGE","Le fichier CV dépasse la taille autorisée.",null);validateSignature(bytes,lower);String hash=HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(bytes));String ext=lower.endsWith(".pdf")?".pdf":".docx";String stored=UUID.randomUUID()+ext;Files.write(resolve(stored),bytes,StandardOpenOption.CREATE_NEW);return new StoredCv(name,stored,mime,bytes.length,hash);}catch(IOException|NoSuchAlgorithmException e){throw new IllegalStateException(e);}}
 private void validateSignature(byte[] bytes,String name){try{if(name.endsWith(".pdf")){if(bytes.length<5||!new String(bytes,0,5).equals("%PDF-"))throw new IOException();}else{try(var zip=new ZipInputStream(new ByteArrayInputStream(bytes))){boolean ok=false;for(ZipEntry e;(e=zip.getNextEntry())!=null;)if("word/document.xml".equals(e.getName()))ok=true;if(!ok)throw new IOException();}}}catch(IOException e){throw error("FILE_INVALID","Le fichier CV est corrompu.");}}
 public Path resolve(String stored){Path path=root.resolve(stored).normalize();if(!path.getParent().equals(root))throw error("INVALID_STORAGE_PATH","Le chemin de stockage est invalide.");return path;}
 public void delete(String stored){try{Files.deleteIfExists(resolve(stored));}catch(IOException e){throw new IllegalStateException(e);}}
 private ApiError error(String code,String message){return new ApiError(HttpStatus.UNPROCESSABLE_ENTITY,code,message,null);} public record StoredCv(String original,String stored,String mime,int size,String hash){}
}
