package com.trainflow.trainer;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.trainflow.shared.error.ApiError;
import com.trainflow.trainer.dto.*;
import java.nio.file.*; import java.sql.*; import java.util.*;
import org.springframework.data.domain.*; import org.springframework.http.*; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.multipart.MultipartFile;

@Service
public class TrainerService {
 private final TrainerRepository trainers; private final TrainerCvRepository cvs; private final CvStorageService storage; private final CvExtractionGateway extraction; private final CvTextExtractor textExtractor; private final JdbcTemplate jdbc; private final ObjectMapper json;
 public TrainerService(TrainerRepository trainers,TrainerCvRepository cvs,CvStorageService storage,CvExtractionGateway extraction,CvTextExtractor textExtractor,JdbcTemplate jdbc,ObjectMapper json){this.trainers=trainers;this.cvs=cvs;this.storage=storage;this.extraction=extraction;this.textExtractor=textExtractor;this.jdbc=jdbc;this.json=json;}
 public TrainerListResponse list(String search,String specialty,boolean inactive,int page,int size){if(page<1||size<1||size>100)throw validation();Page<Trainer> found=trainers.search(clean(search),clean(specialty),inactive,PageRequest.of(page-1,size,Sort.by("fullName")));return new TrainerListResponse(found.map(this::response).getContent(),found.getTotalElements(),page,size);}
 public TrainerResponse get(UUID id){return response(entity(id));}
 @Transactional public TrainerResponse create(TrainerRequest r){Trainer t=new Trainer(required(r.fullName()));apply(t,r);trainers.save(t);log("TrainerCreated","trainer",t.getId(),null,Map.of());return response(t);}
 @Transactional public TrainerResponse patch(UUID id,TrainerPatchRequest r){Trainer t=entity(id);if(r.fullName()!=null)t.setFullName(required(r.fullName()));if(r.firstName()!=null)t.setFirstName(clean(r.firstName()));if(r.lastName()!=null)t.setLastName(clean(r.lastName()));if(r.email()!=null)t.setEmail(clean(r.email()));if(r.phone()!=null)t.setPhone(clean(r.phone()));if(r.mobilePhone()!=null)t.setMobilePhone(clean(r.mobilePhone()));if(r.birthDate()!=null)t.setBirthDate(clean(r.birthDate()));if(r.birthPlace()!=null)t.setBirthPlace(clean(r.birthPlace()));if(r.address()!=null)t.setAddress(clean(r.address()));if(r.company()!=null)t.setCompany(clean(r.company()));if(r.employerAddress()!=null)t.setEmployerAddress(clean(r.employerAddress()));if(r.jobTitle()!=null)t.setJobTitle(clean(r.jobTitle()));if(r.yearsExperience()!=null)t.setYearsExperience(r.yearsExperience());if(r.hourlyRate()!=null)t.setHourlyRate(r.hourlyRate());if(r.dailyRate()!=null)t.setDailyRate(r.dailyRate());if(r.city()!=null)t.setCity(clean(r.city()));if(r.country()!=null)t.setCountry(clean(r.country()));if(r.linkedinUrl()!=null)t.setLinkedinUrl(clean(r.linkedinUrl()));if(r.website()!=null)t.setWebsite(clean(r.website()));if(r.notes()!=null)t.setNotes(clean(r.notes()));return response(t);}
 @Transactional public TrainerResponse archive(UUID id){Trainer t=entity(id);t.setActive(false);log("TrainerArchived","trainer",id,null,Map.of());return response(t);}
 public CvListResponse listCvs(int page,int size){if(page<1||size<1||size>100)throw validation();Page<TrainerCv> found=cvs.findAllByOrderByUploadedAtDesc(PageRequest.of(page-1,size));return new CvListResponse(found.map(this::cvResponse).getContent(),found.getTotalElements(),page,size);}
 public CvResponse getCv(UUID id){return cvResponse(cvEntity(id));}
 @Transactional public CvResponse upload(MultipartFile file){var saved=storage.store(file);if(cvs.findBySha256(saved.hash()).isPresent()){storage.delete(saved.stored());throw new ApiError(HttpStatus.CONFLICT,"CV_ALREADY_EXISTS","Ce CV a déjà été importé.");}TrainerCv cv=cvs.save(new TrainerCv(saved.original(),saved.stored(),saved.mime(),saved.size(),saved.hash()));log("CVUploaded","trainer_cv",cv.getId(),null,Map.of("sha256",saved.hash()));return cvResponse(cv);}
 @Transactional public void deleteCv(UUID id){TrainerCv cv=cvEntity(id);storage.delete(cv.getStorageFilename());cvs.delete(cv);log("CVDeleted","trainer_cv",id,null,Map.of("storage_filename",cv.getStorageFilename()));}
 @Transactional public CvResponse extract(UUID id){TrainerCv cv=cvEntity(id);if("VALIDATED".equals(cv.getExtractionStatus()))throw new ApiError(HttpStatus.CONFLICT,"CV_ALREADY_VALIDATED","Ce CV est déjà validé.");if(cv.getRawText()==null)try{cv.setRawText(textExtractor.extract(storage.resolve(cv.getStorageFilename()),cv.getMimeType()));}catch(Exception e){cv.setExtractionStatus("REVIEW_REQUIRED");cv.setExtractionErrorCode("TEXT_EXTRACTION_FAILED");cv.setExtractionError("Le texte du CV n'a pas pu être extrait. La saisie manuelle reste possible.");return cvResponse(cv);}return cvResponse(extraction.extract(cv));}
 @Transactional public TrainerResponse validate(UUID id,TrainerRequest r){TrainerCv cv=cvEntity(id);if(!Set.of("REVIEW_REQUIRED","AI_ANALYSIS_COMPLETED").contains(cv.getExtractionStatus()))throw new ApiError(HttpStatus.CONFLICT,"CV_NOT_READY","Le CV doit d’abord être vérifié manuellement.");Trainer t=new Trainer(required(r.fullName()));apply(t,r);trainers.save(t);cv.setTrainerId(t.getId());cv.setExtractionStatus("VALIDATED");log("TrainerCreated","trainer",t.getId(),null,Map.of("source","validated_cv","cv_id",id.toString()));return response(t);}
 public ResourceCv trainerCv(UUID trainerId){entity(trainerId);TrainerCv cv=cvs.findFirstByTrainerIdOrderByUploadedAtDesc(trainerId).orElseThrow(()->new ApiError(HttpStatus.NOT_FOUND,"TRAINER_CV_NOT_FOUND","Aucun CV n’est associé à ce formateur."));Path path=storage.resolve(cv.getStorageFilename());if(!Files.isRegularFile(path))throw new ApiError(HttpStatus.NOT_FOUND,"TRAINER_CV_FILE_NOT_FOUND","Le fichier du CV est introuvable.");return new ResourceCv(path,cv.getMimeType(),cv.getOriginalFilename());}
 @Transactional public Map<String,Object> assign(UUID caseId,UUID trainerId){List<Map<String,Object>> rows=jdbc.queryForList("select id,is_archived from training_cases where id=?",caseId.toString());if(rows.isEmpty())throw new ApiError(HttpStatus.NOT_FOUND,"TRAINING_CASE_NOT_FOUND","Le dossier est introuvable.");if(Boolean.TRUE.equals(rows.getFirst().get("is_archived"))||asBoolean(rows.getFirst().get("is_archived")))throw new ApiError(HttpStatus.CONFLICT,"CASE_ARCHIVED","Un dossier archivé ne peut plus être modifié.");Trainer trainer=trainerId==null?null:entity(trainerId);if(trainer!=null&&!trainer.isActive())throw new ApiError(HttpStatus.CONFLICT,"TRAINER_INACTIVE","Ce formateur est inactif.");jdbc.update("update training_cases set trainer_id=?,updated_at=current_timestamp(6) where id=?",trainerId==null?null:trainerId.toString(),caseId.toString());log(trainer==null?"TrainerUnassigned":"TrainerAssigned","training_case",caseId,caseId,Map.of("trainer_id",trainerId==null?"":trainerId.toString()));return caseView(caseId);}
 private Map<String,Object> caseView(UUID id){Map<String,Object> row=jdbc.queryForMap("select tc.*,c.name company_name,t.full_name trainer_name,t.job_title trainer_job_title from training_cases tc join companies c on c.id=tc.company_id left join trainers t on t.id=tc.trainer_id where tc.id=?",id.toString());Map<String,Object> out=new LinkedHashMap<>();for(String key:List.of("id","reference","theme","description","status","desired_start_date","desired_end_date","created_at","updated_at","closed_at","is_archived"))out.put(key,row.get(key));out.put("company",Map.of("id",row.get("company_id"),"name",row.get("company_name")));out.put("primary_contact",null);out.put("trainer",row.get("trainer_id")==null?null:Map.of("id",row.get("trainer_id"),"full_name",row.get("trainer_name"),"job_title",Optional.ofNullable(row.get("trainer_job_title")).orElse("")));return out;}
 private void apply(Trainer t,TrainerRequest r){t.setFirstName(clean(r.firstName()));t.setLastName(clean(r.lastName()));t.setFullName(required(r.fullName()));t.setEmail(clean(r.email()));t.setPhone(clean(r.phone()));t.setMobilePhone(clean(r.mobilePhone()));t.setBirthDate(clean(r.birthDate()));t.setBirthPlace(clean(r.birthPlace()));t.setAddress(clean(r.address()));t.setCompany(clean(r.company()));t.setEmployerAddress(clean(r.employerAddress()));t.setJobTitle(clean(r.jobTitle()));t.setYearsExperience(r.yearsExperience());t.setHourlyRate(r.hourlyRate());t.setDailyRate(r.dailyRate());t.setCity(clean(r.city()));t.setCountry(clean(r.country()));t.setLinkedinUrl(clean(r.linkedinUrl()));t.setWebsite(clean(r.website()));t.setNotes(clean(r.notes()));}
 private Trainer entity(UUID id){return trainers.findById(id).orElseThrow(()->new ApiError(HttpStatus.NOT_FOUND,"TRAINER_NOT_FOUND","Le formateur est introuvable."));} private TrainerCv cvEntity(UUID id){return cvs.findById(id).orElseThrow(()->new ApiError(HttpStatus.NOT_FOUND,"CV_NOT_FOUND","Le CV est introuvable."));}
 private TrainerResponse response(Trainer t){UUID cv=cvs.findFirstByTrainerIdOrderByUploadedAtDesc(t.getId()).map(TrainerCv::getId).orElse(null);return new TrainerResponse(t.getId(),t.getFirstName(),t.getLastName(),t.getFullName(),t.getEmail(),t.getPhone(),t.getMobilePhone(),t.getBirthDate(),t.getBirthPlace(),t.getAddress(),t.getCompany(),t.getEmployerAddress(),t.getJobTitle(),t.getYearsExperience(),t.getHourlyRate(),t.getDailyRate(),t.getCity(),t.getCountry(),t.getLinkedinUrl(),t.getWebsite(),t.getNotes(),cv,t.isActive(),t.getCreatedAt(),t.getUpdatedAt());}
 private CvResponse cvResponse(TrainerCv c){return new CvResponse(c.getId(),c.getTrainerId(),c.getOriginalFilename(),c.getMimeType(),c.getFileSize(),c.getSha256(),c.getUploadedAt(),c.getExtractionStatus(),c.getExtractionModel(),c.getExtractionDurationMs(),c.getParsedJson(),c.getExtractionError(),c.getExtractionErrorCode());}
 private void log(String action,String type,UUID entity,UUID caseId,Map<String,Object> details){try{jdbc.update("insert into activity_logs(id,administrator_id,training_case_id,action,entity_type,entity_id,details) values(?,null,?,?,?,?,?)",UUID.randomUUID().toString(),caseId==null?null:caseId.toString(),action,type,entity.toString(),json.writeValueAsString(details));}catch(JsonProcessingException e){throw new IllegalStateException(e);}}
 private String clean(String v){if(v==null)return null;String c=v.trim().replaceAll("\\s+"," ");return c.isEmpty()?null:c;} private String required(String v){String c=clean(v);if(c==null)throw validation();return c;} private ApiError validation(){return new ApiError(HttpStatus.UNPROCESSABLE_ENTITY,"VALIDATION_ERROR","Les données envoyées sont invalides.");} private boolean asBoolean(Object v){return v instanceof Number n&&n.intValue()!=0;}
 public record ResourceCv(Path path,String mime,String filename){}
}
