package com.trainflow.trainingneed;
import static org.assertj.core.api.Assertions.*; import static org.mockito.ArgumentMatchers.*; import static org.mockito.Mockito.*;
import com.trainflow.shared.error.ApiError; import com.trainflow.trainer.Trainer; import com.trainflow.trainingcase.*; import java.math.BigDecimal; import java.time.LocalDate; import java.util.*; import org.junit.jupiter.api.*; import org.mockito.*; import org.springframework.security.authentication.UsernamePasswordAuthenticationToken; import org.springframework.security.core.context.SecurityContextHolder;
class TrainingNeedServiceTest {
 @Mock TrainingNeedRepository needs; @Mock TrainingCaseRepository cases; @Mock ActivityRepository activities; TrainingNeedService service; UUID caseId=UUID.randomUUID(); TrainingCase trainingCase;
 @BeforeEach void setup(){MockitoAnnotations.openMocks(this);SecurityContextHolder.getContext().setAuthentication(new UsernamePasswordAuthenticationToken(UUID.randomUUID().toString(),null));service=new TrainingNeedService(needs,cases,activities);trainingCase=mock(TrainingCase.class);when(trainingCase.getId()).thenReturn(caseId);when(trainingCase.getTrainer()).thenReturn(mock(Trainer.class));when(trainingCase.getStatus()).thenReturn(TrainingCaseStatus.FORMATEUR_ACCEPTE);when(cases.locked(caseId)).thenReturn(Optional.of(trainingCase));when(needs.saveAndFlush(any())).thenAnswer(i->{TrainingNeed n=i.getArgument(0);n.insert();return n;});}
 @AfterEach void clear(){SecurityContextHolder.clearContext();}
 @Test void createsSingleNeedAndMovesCaseStep(){var result=service.create(caseId,request());assertThat(result.trainingCaseId()).isEqualTo(caseId);verify(trainingCase).setStatus(TrainingCaseStatus.BESOIN_A_COMPLETER);verify(activities).save(any());}
 @Test void rejectsDuplicateNeed(){when(needs.findByTrainingCaseId(caseId)).thenReturn(Optional.of(new TrainingNeed(caseId)));assertThatThrownBy(()->service.create(caseId,request())).isInstanceOf(ApiError.class).extracting("code").isEqualTo("TRAINING_NEED_ALREADY_EXISTS");}
 @Test void rejectsIncoherentPlannedPeriod(){TrainingNeedRequest bad=new TrainingNeedRequest("Public",TrainingNeedLevel.BEGINNER,"Tunis",10,DeliveryMode.PRESENTIEL,new BigDecimal("12"),3,"Objectifs",LocalDate.of(2026,10,1),LocalDate.of(2026,10,5),null);assertThatThrownBy(()->service.create(caseId,bad)).isInstanceOf(ApiError.class).extracting("code").isEqualTo("INVALID_TRAINING_NEED_PLANNED_PERIOD");}
 private TrainingNeedRequest request(){return new TrainingNeedRequest("Employés",TrainingNeedLevel.BEGINNER,"Tunis",10,DeliveryMode.PRESENTIEL,new BigDecimal("12"),3,"Maîtriser les fondamentaux",LocalDate.of(2026,10,1),LocalDate.of(2026,10,3),null);}
}
