package com.trainflow.trainingcase;
import com.trainflow.company.*; import com.trainflow.shared.error.ApiError; import com.trainflow.trainingcase.dto.*; import java.time.*; import java.util.*; import org.springframework.data.domain.*; import org.springframework.data.jpa.domain.Specification; import org.springframework.http.HttpStatus; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.security.core.context.SecurityContextHolder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class TrainingCaseService {
 private final TrainingCaseRepository cases; private final ActivityRepository activities; private final CompanyRepository companies; private final CompanyContactRepository contacts; private final TrainingCatalogRepository catalog; private final JdbcTemplate jdbc; private final TrainingCaseReferenceLock referenceLock;
 private static final Map<TrainingCaseStatus,Set<TrainingCaseStatus>> TRANSITIONS=Map.of(TrainingCaseStatus.BROUILLON,Set.of(TrainingCaseStatus.DEMANDE_RECUE),TrainingCaseStatus.DEMANDE_RECUE,Set.of(TrainingCaseStatus.RECHERCHE_FORMATEUR),TrainingCaseStatus.RECHERCHE_FORMATEUR,Set.of(TrainingCaseStatus.FORMATEUR_PROPOSE),TrainingCaseStatus.FORMATEUR_PROPOSE,Set.of(TrainingCaseStatus.FORMATEUR_ACCEPTE),TrainingCaseStatus.FORMATEUR_ACCEPTE,Set.of(TrainingCaseStatus.BESOIN_A_COMPLETER),TrainingCaseStatus.BESOIN_COMPLETE,Set.of(TrainingCaseStatus.PROGRAMME_EN_PREPARATION));
 public TrainingCaseService(TrainingCaseRepository c,ActivityRepository a,CompanyRepository companies,CompanyContactRepository contacts,TrainingCatalogRepository catalog,JdbcTemplate jdbc,TrainingCaseReferenceLock referenceLock){cases=c;activities=a;this.companies=companies;this.contacts=contacts;this.catalog=catalog;this.jdbc=jdbc;this.referenceLock=referenceLock;}
 @Transactional(readOnly=true) public TrainingCaseResponse get(UUID id){return response(entity(id));}
 public TrainingCaseResponse create(TrainingCaseRequest r){int year=Year.now(ZoneOffset.UTC).getValue();return referenceLock.execute(year,()->createWithReservedReference(r,year));}
 private TrainingCaseResponse createWithReservedReference(TrainingCaseRequest r,int year){Company company=company(r.companyId());CompanyContact contact=contact(company,r.primaryContactId());dates(r.desiredStartDate(),r.desiredEndDate());int number=cases.lastSequence(year).orElse(0)+1;TrainingCase c=new TrainingCase("TR-%d-%05d".formatted(year,number),year,number,company,required(r.theme()),admin());c.setPrimaryContact(contact);c.setDescription(clean(r.description()));c.setDesiredStartDate(r.desiredStartDate());c.setDesiredEndDate(r.desiredEndDate());cases.saveAndFlush(c);log(c,"CREATION",Map.of());return response(c);}
 @Transactional public TrainingCaseResponse patch(UUID id,TrainingCasePatchRequest r){TrainingCase c=entity(id);editable(c);Company company=r.companyId()==null?c.getCompany():company(r.companyId());CompanyContact contact=r.primaryContactId()==null?c.getPrimaryContact():contact(company,r.primaryContactId());LocalDate start=r.desiredStartDate()==null?c.getDesiredStartDate():r.desiredStartDate(),end=r.desiredEndDate()==null?c.getDesiredEndDate():r.desiredEndDate();dates(start,end);c.setCompany(company);c.setPrimaryContact(contact);if(r.theme()!=null)c.setTheme(required(r.theme()));if(r.description()!=null)c.setDescription(clean(r.description()));if(r.desiredStartDate()!=null)c.setDesiredStartDate(start);if(r.desiredEndDate()!=null)c.setDesiredEndDate(end);log(c,"MODIFICATION",Map.of());return response(c);}
 @Transactional public TrainingCaseResponse change(UUID id,TrainingCaseStatus target){TrainingCase c=entity(id);if((target==TrainingCaseStatus.FORMATEUR_PROPOSE||target==TrainingCaseStatus.FORMATEUR_ACCEPTE)&&c.getTrainer()==null)throw conflict("TRAINER_REQUIRED","Un formateur doit être affecté au dossier.");if(target==TrainingCaseStatus.PROGRAMME_EN_PREPARATION)programPrerequisites(c);if(!TRANSITIONS.getOrDefault(c.getStatus(),Set.of()).contains(target))throw conflict("INVALID_STATUS_TRANSITION","Transition de %s vers %s non autorisée.".formatted(c.getStatus(),target));String action=target==TrainingCaseStatus.FORMATEUR_PROPOSE?"TrainerProposed":target==TrainingCaseStatus.FORMATEUR_ACCEPTE?"TrainerAccepted":"CHANGEMENT_STATUT";setStatus(c,target,action);return response(c);}
 @Transactional public TrainingCaseResponse cancel(UUID id){TrainingCase c=entity(id);if(!Set.of(TrainingCaseStatus.BROUILLON,TrainingCaseStatus.DEMANDE_RECUE,TrainingCaseStatus.RECHERCHE_FORMATEUR).contains(c.getStatus()))throw conflict("CASE_NOT_CANCELLABLE","Ce dossier ne peut pas être annulé.");setStatus(c,TrainingCaseStatus.ANNULE,"ANNULATION");return response(c);}
 @Transactional public TrainingCaseResponse close(UUID id){TrainingCase c=entity(id);if(c.getStatus()!=TrainingCaseStatus.DOCUMENTS_GENERES)throw conflict("CASE_NOT_CLOSABLE","Ce dossier ne peut pas être clôturé.");c.setClosedAt(Instant.now());setStatus(c,TrainingCaseStatus.TERMINE,"CLOTURE");return response(c);}
 @Transactional public TrainingCaseResponse archive(UUID id){TrainingCase c=entity(id);if(!Set.of(TrainingCaseStatus.TERMINE,TrainingCaseStatus.ANNULE).contains(c.getStatus()))throw conflict("CASE_NOT_ARCHIVABLE","Seul un dossier terminé ou annulé peut être archivé.");c.setStatus(TrainingCaseStatus.ARCHIVE);c.setArchived(true);log(c,"ARCHIVAGE",Map.of());return response(c);}
 @Transactional(readOnly=true) public TrainingCaseListResponse list(String reference,UUID companyId,String theme,TrainingCaseStatus status,LocalDate createdFrom,LocalDate createdTo,LocalDate startFrom,LocalDate startTo,boolean archived,int page,int size,String sortBy,String order){if(page<1||size<1||size>100||!Set.of("createdAt","updatedAt","reference").contains(sortBy))throw validation();Specification<TrainingCase> s=(root,q,cb)->cb.conjunction();if(!archived)s=s.and((r,q,cb)->cb.isFalse(r.get("archived")));if(clean(reference)!=null)s=s.and((r,q,cb)->cb.like(cb.lower(r.get("reference")),"%"+clean(reference).toLowerCase()+"%"));if(companyId!=null)s=s.and((r,q,cb)->cb.equal(r.get("company").get("id"),companyId));if(clean(theme)!=null)s=s.and((r,q,cb)->cb.like(cb.lower(r.get("theme")),"%"+clean(theme).toLowerCase()+"%"));if(status!=null)s=s.and((r,q,cb)->cb.equal(r.get("status"),status));if(createdFrom!=null)s=s.and((r,q,cb)->cb.greaterThanOrEqualTo(r.get("createdAt"),createdFrom.atStartOfDay(ZoneOffset.UTC).toInstant()));if(createdTo!=null)s=s.and((r,q,cb)->cb.lessThan(r.get("createdAt"),createdTo.plusDays(1).atStartOfDay(ZoneOffset.UTC).toInstant()));if(startFrom!=null)s=s.and((r,q,cb)->cb.greaterThanOrEqualTo(r.get("desiredStartDate"),startFrom));if(startTo!=null)s=s.and((r,q,cb)->cb.lessThanOrEqualTo(r.get("desiredStartDate"),startTo));Sort sort=Sort.by("asc".equalsIgnoreCase(order)?Sort.Direction.ASC:Sort.Direction.DESC,sortBy);Page<TrainingCase> p=cases.findAll(s,PageRequest.of(page-1,size,sort));return new TrainingCaseListResponse(p.stream().map(this::response).toList(),p.getTotalElements(),page,size);}
 @Transactional(readOnly=true) public List<ActivityResponse> activity(UUID id){entity(id);return activities.findByTrainingCaseIdOrderByCreatedAtDesc(id).stream().map(a->new ActivityResponse(a.getId(),a.getAction(),a.getDetails(),a.getCreatedAt())).toList();}
 @Transactional(readOnly=true) public DashboardResponse dashboard(){long archived=cases.count((r,q,cb)->cb.isTrue(r.get("archived")));long cancelled=cases.count((r,q,cb)->cb.and(cb.isFalse(r.get("archived")),cb.equal(r.get("status"),TrainingCaseStatus.ANNULE)));long active=cases.count((r,q,cb)->cb.and(cb.isFalse(r.get("archived")),cb.notEqual(r.get("status"),TrainingCaseStatus.ANNULE)));Page<TrainingCase> recent=cases.findAll((r,q,cb)->cb.isFalse(r.get("archived")),PageRequest.of(0,5,Sort.by(Sort.Direction.DESC,"createdAt")));return new DashboardResponse(active,cancelled,archived,recent.stream().map(this::response).toList());}
 public List<CatalogItemResponse> catalog(){return catalog.findByActiveTrueOrderByCategoryAscTitleAsc().stream().map(i->new CatalogItemResponse(i.getId(),i.getCategory(),i.getTitle())).toList();}
 private void programPrerequisites(TrainingCase c){if(c.getTrainer()==null)throw conflict("TRAINER_REQUIRED","Un formateur doit être affecté au dossier.");Integer count=jdbc.queryForObject("select count(*) from training_needs where training_case_id=? and is_validated=true",Integer.class,c.getId().toString());if(count==null||count==0)throw conflict("TRAINING_NEED_NOT_VALIDATED","Le besoin client doit être validé avant de préparer le programme.");}
 private void setStatus(TrainingCase c,TrainingCaseStatus target,String action){var old=c.getStatus();c.setStatus(target);log(c,action,Map.of("previous_status",old.name(),"new_status",target.name()));}
 private void log(TrainingCase c,String action,Map<String,Object>d){activities.save(new ActivityLog(admin(),c.getId(),action,d));} private UUID admin(){return UUID.fromString(SecurityContextHolder.getContext().getAuthentication().getName());}
 private TrainingCase entity(UUID id){return cases.detailed(id).orElseThrow(()->new ApiError(HttpStatus.NOT_FOUND,"TRAINING_CASE_NOT_FOUND","Le dossier est introuvable."));} private Company company(UUID id){Company c=companies.findById(id).orElseThrow(()->new ApiError(HttpStatus.NOT_FOUND,"COMPANY_NOT_FOUND","L’entreprise est introuvable."));if(c.isArchived())throw conflict("COMPANY_ARCHIVED","Une entreprise archivée ne peut pas être associée à un nouveau dossier.");return c;} private CompanyContact contact(Company c,UUID id){if(id==null)return null;CompanyContact x=contacts.findById(id).orElseThrow(()->new ApiError(HttpStatus.NOT_FOUND,"CONTACT_NOT_FOUND","Le contact est introuvable."));if(!x.getCompany().getId().equals(c.getId()))throw conflict("CONTACT_COMPANY_MISMATCH","Le contact n’appartient pas à l’entreprise sélectionnée.");return x;}
 private void editable(TrainingCase c){if(c.isArchived())throw conflict("CASE_ARCHIVED","Un dossier archivé ne peut plus être modifié.");} private void dates(LocalDate a,LocalDate b){if(a!=null&&b!=null&&b.isBefore(a))throw new ApiError(HttpStatus.UNPROCESSABLE_ENTITY,"INVALID_DATE_RANGE","La date de fin ne peut pas précéder la date de début.");}
 private TrainingCaseResponse response(TrainingCase c){var company=new TrainingCaseResponse.CompanySummary(c.getCompany().getId(),c.getCompany().getName());var contact=c.getPrimaryContact()==null?null:new TrainingCaseResponse.ContactSummary(c.getPrimaryContact().getId(),c.getPrimaryContact().getFullName(),c.getPrimaryContact().getEmail(),c.getPrimaryContact().getPhone(),c.getPrimaryContact().getJobTitle(),c.getPrimaryContact().isPrimary(),c.getPrimaryContact().getCreatedAt(),c.getPrimaryContact().getUpdatedAt());var trainer=c.getTrainer()==null?null:new TrainingCaseResponse.TrainerSummary(c.getTrainer().getId(),c.getTrainer().getFullName(),c.getTrainer().getJobTitle());return new TrainingCaseResponse(c.getId(),c.getReference(),company,contact,trainer,c.getTheme(),c.getDescription(),c.getStatus(),c.getDesiredStartDate(),c.getDesiredEndDate(),c.getCreatedAt(),c.getUpdatedAt(),c.getClosedAt(),c.isArchived());}
 private String clean(String s){if(s==null)return null;String v=s.trim().replaceAll("\\s+"," ");return v.isBlank()?null:v;}private String required(String s){String v=clean(s);if(v==null)throw validation();return v;} private ApiError conflict(String c,String m){return new ApiError(HttpStatus.CONFLICT,c,m);} private ApiError validation(){return new ApiError(HttpStatus.UNPROCESSABLE_ENTITY,"VALIDATION_ERROR","Les données envoyées sont invalides.");}
}
