package com.trainflow.trainingcase;
import static org.assertj.core.api.Assertions.*; import static org.mockito.ArgumentMatchers.*; import static org.mockito.Mockito.*;
import com.trainflow.company.*; import com.trainflow.shared.error.ApiError; import com.trainflow.trainingcase.dto.*; import java.util.*; import org.junit.jupiter.api.*; import org.mockito.*; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.security.authentication.UsernamePasswordAuthenticationToken; import org.springframework.security.core.context.SecurityContextHolder;
class TrainingCaseServiceTest {
 @Mock TrainingCaseRepository cases; @Mock ActivityRepository activities; @Mock CompanyRepository companies; @Mock CompanyContactRepository contacts; @Mock TrainingCatalogRepository catalog; @Mock JdbcTemplate jdbc; @Mock TrainingCaseReferenceLock referenceLock; TrainingCaseService service; Company company; UUID admin=UUID.randomUUID();
 @BeforeEach void setup(){MockitoAnnotations.openMocks(this);SecurityContextHolder.getContext().setAuthentication(new UsernamePasswordAuthenticationToken(admin,null));when(referenceLock.execute(anyInt(),any())).thenAnswer(i->((java.util.function.Supplier<?>)i.getArgument(1)).get());service=new TrainingCaseService(cases,activities,companies,contacts,catalog,jdbc,referenceLock);company=mock(Company.class);when(company.getId()).thenReturn(UUID.randomUUID());when(company.getName()).thenReturn("ABC Conseil");when(companies.findById(company.getId())).thenReturn(Optional.of(company));when(cases.saveAndFlush(any())).thenAnswer(i->{TrainingCase c=i.getArgument(0);c.insert();return c;});}
 @AfterEach void clear(){SecurityContextHolder.clearContext();}
 @Test void generatesSequentialReferences(){when(cases.lastSequence(anyInt())).thenReturn(Optional.empty(),Optional.of(1));var request=new TrainingCaseRequest(company.getId(),null,"Management",null,null,null);assertThat(service.create(request).reference()).matches("TR-\\d{4}-00001");assertThat(service.create(request).reference()).matches("TR-\\d{4}-00002");verify(referenceLock,times(2)).execute(eq(java.time.Year.now().getValue()),any());verify(cases,times(2)).lastSequence(java.time.Year.now().getValue());}
 @Test void acceptsValidTransitionAndRejectsInvalidOne(){TrainingCase c=caseWith(TrainingCaseStatus.BROUILLON);when(cases.detailed(c.getId())).thenReturn(Optional.of(c));assertThat(service.change(c.getId(),TrainingCaseStatus.DEMANDE_RECUE).status()).isEqualTo(TrainingCaseStatus.DEMANDE_RECUE);assertThatThrownBy(()->service.change(c.getId(),TrainingCaseStatus.PROGRAMME_VALIDE)).isInstanceOf(ApiError.class).extracting("code").isEqualTo("INVALID_STATUS_TRANSITION");}
 @Test void cancellationAndArchiveFollowWorkflow(){TrainingCase c=caseWith(TrainingCaseStatus.BROUILLON);when(cases.detailed(c.getId())).thenReturn(Optional.of(c));assertThat(service.cancel(c.getId()).status()).isEqualTo(TrainingCaseStatus.ANNULE);assertThat(service.archive(c.getId()).isArchived()).isTrue();}
 @Test void rejectsArchivingActiveCase(){TrainingCase c=caseWith(TrainingCaseStatus.DEMANDE_RECUE);when(cases.detailed(c.getId())).thenReturn(Optional.of(c));assertThatThrownBy(()->service.archive(c.getId())).isInstanceOf(ApiError.class).extracting("code").isEqualTo("CASE_NOT_ARCHIVABLE");}
 private TrainingCase caseWith(TrainingCaseStatus status){TrainingCase c=new TrainingCase("TR-2026-00001",2026,1,company,"Management",admin);c.insert();c.setStatus(status);return c;}
}
