package com.trainflow.program;
import static org.assertj.core.api.Assertions.*; import static org.mockito.ArgumentMatchers.*; import static org.mockito.Mockito.*;
import com.trainflow.shared.error.ApiError; import com.trainflow.trainer.Trainer; import com.trainflow.trainingcase.*; import com.trainflow.trainingneed.*; import java.math.BigDecimal; import java.util.*; import java.util.concurrent.atomic.AtomicReference; import org.junit.jupiter.api.*; import org.mockito.*; import org.springframework.security.authentication.UsernamePasswordAuthenticationToken; import org.springframework.security.core.context.SecurityContextHolder;
class ProgramServiceTest {
 @Mock TrainingProgramRepository programs;@Mock TrainingProgramDayRepository days;@Mock TrainingProgramItemRepository items;@Mock TrainingCaseRepository cases;@Mock TrainingNeedRepository needs;@Mock ActivityRepository activities;@Mock ProgramGenerationGateway generator;ProgramService service;UUID caseId=UUID.randomUUID();TrainingCase trainingCase;TrainingNeed need;AtomicReference<TrainingCaseStatus> status;
 @BeforeEach void setup(){MockitoAnnotations.openMocks(this);SecurityContextHolder.getContext().setAuthentication(new UsernamePasswordAuthenticationToken(UUID.randomUUID().toString(),null));service=new ProgramService(programs,days,items,cases,needs,activities,generator);trainingCase=mock(TrainingCase.class);status=new AtomicReference<>(TrainingCaseStatus.BESOIN_COMPLETE);when(trainingCase.getId()).thenReturn(caseId);when(trainingCase.getTrainer()).thenReturn(mock(Trainer.class));when(trainingCase.getStatus()).thenAnswer(i->status.get());doAnswer(i->{status.set(i.getArgument(0));return null;}).when(trainingCase).setStatus(any());when(cases.locked(caseId)).thenReturn(Optional.of(trainingCase));need=mock(TrainingNeed.class);when(need.isValidated()).thenReturn(true);when(need.getDurationHours()).thenReturn(new BigDecimal("1"));when(needs.findByTrainingCaseId(caseId)).thenReturn(Optional.of(need));when(programs.saveAndFlush(any())).thenAnswer(i->{TrainingProgram p=i.getArgument(0);p.insert();return p;});when(days.save(any())).thenAnswer(i->{TrainingProgramDay d=i.getArgument(0);d.insert();return d;});when(items.save(any())).thenAnswer(i->{TrainingProgramItem x=i.getArgument(0);x.insert();return x;});}
 @AfterEach void clear(){SecurityContextHolder.clearContext();}
 @Test void manualProgramCanBeSubmittedWhenDurationMatches(){ProgramResponse created=service.create(caseId,new ProgramRequest("Programme",null,null,"Quiz"));TrainingProgram p=programs.saveAndFlush(new TrainingProgram(caseId,"Programme"));p.insert();when(programs.locked(caseId)).thenReturn(Optional.of(p));status.set(TrainingCaseStatus.PROGRAMME_EN_PREPARATION);ProgramResponse withDay=service.addDay(caseId,new DayRequest("Jour 1"));UUID dayId=withDay.days().getFirst().id();service.addItem(caseId,dayId,new ItemRequest(ProgramItemType.MODULE,null,"Fondamentaux",null,30,30,Set.of(PedagogicalMethod.EXPOSE)));ProgramResponse submitted=service.submit(caseId);assertThat(created.title()).isEqualTo("Programme");assertThat(submitted.isSubmitted()).isTrue();assertThat(submitted.totalMinutes()).isEqualTo(60);}
 @Test void rejectsDurationMismatch(){TrainingProgram p=new TrainingProgram(caseId,"Programme");p.insert();when(programs.locked(caseId)).thenReturn(Optional.of(p));status.set(TrainingCaseStatus.PROGRAMME_EN_PREPARATION);assertThatThrownBy(()->service.submit(caseId)).isInstanceOf(ApiError.class);}
 @Test void submittedProgramIsNotEditable(){TrainingProgram p=new TrainingProgram(caseId,"Programme");p.insert();p.setSubmitted(true);when(programs.locked(caseId)).thenReturn(Optional.of(p));status.set(TrainingCaseStatus.PROGRAMME_A_VALIDER);assertThatThrownBy(()->service.addDay(caseId,new DayRequest("Jour"))).isInstanceOf(ApiError.class).extracting("code").isEqualTo("TRAINING_PROGRAM_NOT_EDITABLE");}
}
