package com.trainflow.program;
import static org.assertj.core.api.Assertions.*; import static org.mockito.ArgumentMatchers.*; import static org.mockito.Mockito.*;
import com.trainflow.shared.error.ApiError; import com.trainflow.trainer.*; import com.trainflow.trainingcase.*; import com.trainflow.trainingneed.*; import java.math.BigDecimal; import java.util.*; import java.util.concurrent.atomic.AtomicReference; import org.junit.jupiter.api.*; import org.mockito.*; import org.springframework.security.authentication.UsernamePasswordAuthenticationToken; import org.springframework.security.core.context.SecurityContextHolder;
class ProgramServiceTest {
 @Mock TrainingProgramRepository programs;@Mock TrainingProgramDayRepository days;@Mock TrainingProgramItemRepository items;@Mock TrainingCaseRepository cases;@Mock TrainingNeedRepository needs;@Mock ActivityRepository activities;@Mock ProgramGenerationGateway generator;@Mock ProgramGenerationTransactions transactions;@Mock TrainerCvRepository trainerCvs;ProgramService service;UUID caseId=UUID.randomUUID();TrainingCase trainingCase;TrainingNeed need;Trainer trainer;AtomicReference<TrainingCaseStatus> status;
 @BeforeEach void setup(){MockitoAnnotations.openMocks(this);SecurityContextHolder.getContext().setAuthentication(new UsernamePasswordAuthenticationToken(UUID.randomUUID().toString(),null));doAnswer(i->((java.util.function.Supplier<?>)i.getArgument(0)).get()).when(transactions).read(any());doAnswer(i->((java.util.function.Supplier<?>)i.getArgument(0)).get()).when(transactions).write(any());service=new ProgramService(programs,days,items,cases,needs,activities,generator,new ProgramDraftValidator(),transactions,trainerCvs);trainingCase=mock(TrainingCase.class);trainer=mock(Trainer.class);when(trainer.getId()).thenReturn(UUID.randomUUID());when(trainer.getFullName()).thenReturn("Amina");status=new AtomicReference<>(TrainingCaseStatus.BESOIN_COMPLETE);when(trainingCase.getId()).thenReturn(caseId);when(trainingCase.getTheme()).thenReturn("Cybersecurity");when(trainingCase.getTrainer()).thenReturn(trainer);when(trainingCase.getStatus()).thenAnswer(i->status.get());doAnswer(i->{status.set(i.getArgument(0));return null;}).when(trainingCase).setStatus(any());when(cases.locked(caseId)).thenReturn(Optional.of(trainingCase));when(cases.detailed(caseId)).thenReturn(Optional.of(trainingCase));need=mock(TrainingNeed.class);when(need.isValidated()).thenReturn(true);when(need.getDurationHours()).thenReturn(new BigDecimal("1"));when(need.getPlannedDaysCount()).thenReturn(1);when(needs.findByTrainingCaseId(caseId)).thenReturn(Optional.of(need));when(programs.saveAndFlush(any())).thenAnswer(i->{TrainingProgram p=i.getArgument(0);p.insert();return p;});when(days.save(any())).thenAnswer(i->{TrainingProgramDay d=i.getArgument(0);d.insert();return d;});when(items.save(any())).thenAnswer(i->{TrainingProgramItem x=i.getArgument(0);x.insert();return x;});}
 @AfterEach void clear(){SecurityContextHolder.clearContext();}
 @Test void manualProgramCanBeSubmittedWhenDurationMatches(){ProgramResponse created=service.create(caseId,new ProgramRequest("Programme",null,null,"Quiz"));TrainingProgram p=programs.saveAndFlush(new TrainingProgram(caseId,"Programme"));p.insert();when(programs.locked(caseId)).thenReturn(Optional.of(p));status.set(TrainingCaseStatus.PROGRAMME_EN_PREPARATION);ProgramResponse withDay=service.addDay(caseId,new DayRequest("Jour 1"));UUID dayId=withDay.days().getFirst().id();ProgramResponse withItem=service.addItem(caseId,dayId,new ItemRequest(ProgramItemType.MODULE,null,"Fondamentaux",null,30,30,Set.of(PedagogicalMethod.EXPOSE)));ProgramResponse.Item persisted=withItem.days().getFirst().items().getFirst();ProgramResponse submitted=service.submit(caseId);assertThat(created.title()).isEqualTo("Programme");assertThat(persisted.methods()).containsExactly(PedagogicalMethod.EXPOSE);assertThat(persisted.totalMinutes()).isEqualTo(60);assertThat(submitted.isSubmitted()).isTrue();assertThat(submitted.totalMinutes()).isEqualTo(60);}
 @Test void programItemStoresIntegratedMethodAndDuration(){TrainingProgram p=new TrainingProgram(caseId,"Programme");TrainingProgramDay d=new TrainingProgramDay(p,"Jour 1",1);TrainingProgramItem item=new TrainingProgramItem(d,ProgramItemType.MODULE,null,"Atelier",1);item.setTheoryMinutes(15);item.setPracticeMinutes(45);item.getMethods().add(PedagogicalMethod.EXERCICE_PRATIQUE);item.insert();assertThat(item.getMethods()).containsExactly(PedagogicalMethod.EXERCICE_PRATIQUE);assertThat(item.getDurationHours()).isEqualByComparingTo("1.00");}
 @Test void rejectsDurationMismatch(){TrainingProgram p=new TrainingProgram(caseId,"Programme");p.insert();when(programs.locked(caseId)).thenReturn(Optional.of(p));status.set(TrainingCaseStatus.PROGRAMME_EN_PREPARATION);assertThatThrownBy(()->service.submit(caseId)).isInstanceOf(ApiError.class);}
 @Test void submittedProgramIsNotEditable(){TrainingProgram p=new TrainingProgram(caseId,"Programme");p.insert();p.setSubmitted(true);when(programs.locked(caseId)).thenReturn(Optional.of(p));status.set(TrainingCaseStatus.PROGRAMME_A_VALIDER);assertThatThrownBy(()->service.addDay(caseId,new DayRequest("Jour"))).isInstanceOf(ApiError.class).extracting("code").isEqualTo("TRAINING_PROGRAM_NOT_EDITABLE");}
 @Test void generatedProgramIsPersistedOnlyAfterStrictValidation(){when(generator.generate(any())).thenReturn(validDraft());ProgramResponse response=service.generate(caseId);assertThat(response.days()).hasSize(1);assertThat(response.totalMinutes()).isEqualTo(60);verify(programs).saveAndFlush(argThat(program->program.getDays().size()==1&&program.getDays().getFirst().getItems().size()==1));verify(generator).generate(argThat(input->input.totalDurationMinutes()==60&&input.trainer().name().equals("Amina")));}
 @Test void invalidGeneratedProgramIsNeverPersisted(){when(generator.generate(any())).thenReturn(Map.of("title","Incomplete"));assertThatThrownBy(()->service.generate(caseId)).isInstanceOf(ApiError.class).extracting("code").isEqualTo("LLM_INVALID_RESPONSE");verify(programs,never()).saveAndFlush(any());verify(transactions,never()).write(any());}
 private Map<String,Object> validDraft(){return Map.of("title","Cybersecurity","duration_days",1,"days",List.of(Map.of("day_number",1,"title","Day 1","contents",List.of(Map.of("order_index",1,"title","Threats","concepts",List.of("Phishing"),"methods",List.of("EXPOSE"),"theory_minutes",30,"practice_minutes",30)))));}
}
